### PR TITLE
Fix: Student's username link in classroom admin view should link to their portfolio

### LINKED ISSUE #921: BUG: Student's username link in classroom admin view should link to their portfolio
Steps to replicate:

1. Log in as admin or teacher
2. Navigate to `classes` tab on nav bar
3. click on a class
4. click on a students name

We should navigate to that student's portfolio but we're navigating back to the home page.  Might be a permission issue?  I can see when I hover that we are pointing to the portfolio.

Image

### PR DESCRIPTION
**Pull request by gr4yt3x**
# Fix: Student's username link in classroom admin view should link to their portfolio

## Summary
Teachers and admins were unable to access a student’s portfolio from the classroom admin view due to policy restrictions. This change updates the authorization policy so permitted users can view student portfolios as intended.

## Related Issue
Resolves #921

## Changes
- Updated portfolio policy to allow teachers and admins to access student portfolios
- Added policy and feature specs to ensure authorized access

## Checklist
- [x] Issue is assigned (commenting on the issue page is needed)
- [x] Issue link added to the PR's description
- [x] Branch created from main
- [x] Commits are small and descriptive
- [x] Ran linter and fixed issues
- [x] Ran tests and all tests pass

### CODE REVIEW

File: test/policies/portfolio_policy_test.rb [hunk 1]
```diff
@@ -4,12 +4,26 @@
...
+
     @portfolio = Portfolio.create!(user: @student)
     @other_portfolio = Portfolio.create!(user: @other_student)
+
+    TeacherClassroom.create!(teacher: @teacher, classroom: @classroom)
+  end
+
+  test "admin can show any portfolio" do
+    assert PortfolioPolicy.new(@admin, @portfolio).show?
+    assert PortfolioPolicy.new(@admin, @portfolio_in_other_classroom).show?
```
Comment (pollygee) [inline test/policies/portfolio_policy_test.rb]: on line 19 we have `@other_portfolio` defined - is that what we should be using here? I don't see `@portfolio_in_other_classroom` defined anywhere.

**Review by pollygee — CHANGES_REQUESTED** [review]
Thanks for your work here.  I left a couple small comments.  Let me know what you think about those and once we clear those up we can get this merged in.

**Comment by pollygee** [comment]
@gr4yt3x checking if you'll have time to make these updates?  If not I can fix some stuff up and get this merged.  I just wanted to give you the chance to look at it if you want to?
